### ISSUE TITLE
на РЕГИСТРАТОРЕ   MSW ...

### ISSUE THREAD

**Issue by mgf1** [AlienJust/DrillingRig#6]
на РЕГИСТРАТОРЕ отображать на подсказки MSW ASW MCW в виде HEX,
То есть при остановке и просмотре графиков есть вертикальная полоска позиции мыши. на ней отображается значение параметра на графике в этот момент. одновременно показывать MSW ASW MCW в виде HEX, Можно сбоку

**Comment by AlienJust** [comment]
Скачал у Данилы исходники - буду копать :)

**Comment by AlienJust** [comment]
Вроде уже давно реализовано - закрываю
